services:
  - type: web
    name: newsnexus-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn newsnexus.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: newsnexus.settings
      - key: PYTHON_VERSION
        value: 3.10
