services:
  - type: web
    name: newsnexus-backend
    env: python
    plan: free
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && gunicorn newsnexus.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: newsnexus.settings
      - key: PYTHON_VERSION
        value: 3.11
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*"
    staticPublishPath: backend/staticfiles
    autoDeploy: true
